name: oauth1_client
description: An Oauth1 library.
version: 1.0.0
repository: https://github.com/mrtcndnlr/oauth1_client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
